kind: Pod
apiVersion: v1
metadata:
  name: tomcat
  labels:
    app: tomcat
spec:
    containers:
       - name: tomcat
         image: mabasha/myapp:tomcat-1
         ports:
           - containerport: 80
         
